version: "3.2"

services:
  database:
    image: postgres:12
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=snozzle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin999
    ports:
      - "5432:5432"
    container_name: database

  # graphql-engine:
  #   image: hasura/graphql-engine:v2.0.0-alpha.3
  #   ports:
  #   - "8080:8080"
  #   depends_on:
  #   - "database"
  #   restart: always
  #   environment:
  #     HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:Admin999@database:5432/snozzle
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
  #     ## uncomment next line to set an admin secret
  #     # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  #   container_name: hasura